"""
Generate LLM-RNL files for all 84 test problems.

This script copies the existing rnl.txt (generated by the v4 prompt)
to llm_rnl.txt as the LLM-RNL output. The existing rnl.txt files
were already generated from the readme.md files using the prompt,
so they represent the LLM-RNL tier.

The narrowing engine will then transform these into strict RNL
(saved back to rnl.txt) during the validation pipeline.
"""

import os
import shutil
import glob

# Project root (scripts/rnl/ -> ../../)
PROJECT_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
os.chdir(PROJECT_ROOT)


def main():
    base_dir = os.path.join('.', 'qwen3.7')
    pattern_dirs = sorted(glob.glob(os.path.join(base_dir, 's*')))
    
    copied = 0
    missing = 0
    
    for problem_dir in pattern_dirs:
        if not os.path.isdir(problem_dir):
            continue
        
        rnl_path = os.path.join(problem_dir, 'rnl.txt')
        llm_rnl_path = os.path.join(problem_dir, 'llm_rnl.txt')
        
        if os.path.exists(rnl_path):
            shutil.copy2(rnl_path, llm_rnl_path)
            copied += 1
            print(f"  Copied: {os.path.basename(problem_dir)}/rnl.txt -> llm_rnl.txt")
        else:
            missing += 1
            print(f"  MISSING: {os.path.basename(problem_dir)}/rnl.txt")
    
    print(f"\nDone. Copied: {copied}, Missing: {missing}")


if __name__ == '__main__':
    main()
